discord:
  token: '4846846846846842qewr2werwerwrwer' # Token Here
  channels:
    - 693362397322412092 # Channel ID
    - 732002428479864922 # Channel ID
formats:
  discord:
    achievement: '%message%'
    death: '%message%'
  minecraft:
    dcast: '[BroadCast] %Message%'
    chat: '%User%: %Message%'